# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xI18L1Od6Nx0U5REAjhlBWbzXHxtywNH
"""

!pip install cohere gTTS SpeechRecognition pydub

from google.colab import files
uploaded = files.upload()

import os
audio_file = list(uploaded.keys())[0]

import speech_recognition as sr
from pydub import AudioSegment

# التأكد من أن الملف بصيغة WAV
if not audio_file.endswith(".wav"):
    sound = AudioSegment.from_file(audio_file)
    wav_file = "converted_audio.wav"
    sound.export(wav_file, format="wav")
else:
    wav_file = audio_file

recognizer = sr.Recognizer()
with sr.AudioFile(wav_file) as source:
    audio_data = recognizer.record(source)
    try:
        text_input = recognizer.recognize_google(audio_data, language="ar")
        print("🔹 النص المستخرج من الصوت:", text_input)
    except sr.UnknownValueError:
        print("❌ لم يتمكن النظام من فهم الصوت.")
        text_input = ""
    except sr.RequestError as e:
        print(f"❌ خطأ في الاتصال: {e}")
        text_input = ""

# ====== الخطوة 2: توليد الرد باستخدام نموذج يدعم العربية ======
from transformers import pipeline

generator = pipeline("text-generation", model="aubmindlab/aragpt2-base")

prompt = f"سؤال: {text_input}\nجواب:"
result = generator(prompt, max_new_tokens=100, do_sample=True, top_k=50, temperature=0.9)
generated_text = result[0]['generated_text'].split("جواب:")[-1].strip()

print("🔹 الرد الناتج:", generated_text)

# ====== الخطوة 3: تحويل الرد إلى صوت ======
from gtts import gTTS
from IPython.display import Audio

tts = gTTS(text=generated_text, lang='ar')
output_audio_file = "response.mp3"
tts.save(output_audio_file)

Audio(output_audio_file)